name: CI

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    list-and-test:
        runs-on: ubuntu-latest

        steps:
            - name: Check out code
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                go-version: '1.22'
                cache: true
            
            - name: Check formatting
              run: |
                IF_FMT_ERRORS=$(gofmt -l .)
                if [ ! -z "$IF_FMT_ERRORS" ]; then
                    echo "Следующие файлы не отформатированы:"
                    echo "$IF_FMT_ERRORS"
                    exit 1
                fi

            - name: Run vet
              run: go vet ./...

            - name: Run tests with race detector
              run: go test -race ./...
            
